{
 "title": "Orchard Core x Amazon CloudWatch",
 "description": "Visualise Amazon CloudWatch Log based metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "Logs",
  "Orchard Core"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Orchard Core on ECS Dashboard\n\n## Orchard core\nURL: https://orchardcore.net/\n\n## Orchard Core Basics Companion (OCBC)\nURL: https://gcl.gitbook.io/orchard-core-basics-companion-ocbc"
   },
   "targets": [
    { "region": "default", "statistic": "Average" }
   ]
  },
  {
   "title": "cld-core-orchard - Task Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "core-cluster", "ServiceName": "cld-orchard-core" },
     "logGroups": [
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/aws/ecs/containerinsights/core-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/core-cluster/performance"
      }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "cld-core-orchard - Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "core-cluster", "ServiceName": "cld-orchard-core" },
     "logGroups": [
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/aws/ecs/containerinsights/core-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/core-cluster/performance"
      }
     ],
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "cld-orchard-core - CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "core-cluster", "ServiceName": "cld-orchard-core" },
     "logGroups": [
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/aws/ecs/containerinsights/core-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/core-cluster/performance"
      }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "/api/v1/packages Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Endpoint": "/api/v1/packages" },
     "logGroups": [
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/aws/ecs/containerinsights/core-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/core-cluster/performance"
      },
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/ecs/cld-orchard-core-log-group:*",
       "name": "/ecs/cld-orchard-core-log-group"
      }
     ],
     "metricName": "ResponseTimeMs",
     "namespace": "Experiment.OrchardCore.Main/Performance",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "/api/v1/packages Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "dimensions": { "Endpoint": "/api/v1/packages" },
     "logGroups": [
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/aws/ecs/containerinsights/core-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/core-cluster/performance"
      },
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/ecs/cld-orchard-core-log-group:*",
       "name": "/ecs/cld-orchard-core-log-group"
      }
     ],
     "metricName": "Http2xxCount",
     "namespace": "Experiment.OrchardCore.Main/Performance",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    },
    {
     "dimensions": { "Endpoint": "/api/v1/packages" },
     "logGroups": [
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/aws/ecs/containerinsights/core-cluster/performance:*",
       "name": "/aws/ecs/containerinsights/core-cluster/performance"
      },
      {
       "accountId": "982081087543",
       "arn": "arn:aws:logs:ap-southeast-5:982081087543:log-group:/ecs/cld-orchard-core-log-group:*",
       "name": "/ecs/cld-orchard-core-log-group"
      }
     ],
     "metricName": "Http4xxCount",
     "namespace": "Experiment.OrchardCore.Main/Performance",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "cld-orchard-core Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "filters": [
      { "id": "7b79800b", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "cld-orchard-core" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "!=",
       "scope": "span",
       "tag": "name",
       "value": [ "GET /health" ],
       "valueType": "string"
      }
     ],
     "limit": 20
    }
   ]
  },
  {
   "title": "Incoming log events [count/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingLogEvents\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Incoming bytes [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingBytes\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Delivery errors [count]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "metricName": "DeliveryErrors",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Delivery throttling [count]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "metricName": "DeliveryThrottling",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Forwarded log events [count/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"ForwardedLogEvents\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "ForwardedLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Forwarded bytes [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"ForwardedBytes\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "ForwardedBytes",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}